### ISSUE TITLE
训练模型读取数据的问题

### ISSUE THREAD

**Issue by shushenw** [WentianZhang-ML/FRT-PAD#1]
FRT-PAD的作者您好，我是一名机器学习方向的博士生，我最近在做有关liveness detection的测试，看到您的论文水平非常高所以想自己来运行一下。而最近在用您的代码进行测试的时候我遇到了如下问题：在进行训练的时候，训练模型无法读取数据库，具体一点应该是get_dataset函数里的DataLoader无法正确读取输入的dataset。所以我想问下您在之前训练的时候是否有相似的问题，或者说您在data_find步骤，图片用的是怎样的格式，图片的名称是否对后来加载数据库有影响？
非常感谢您的理解和帮助，很期待跟您能有后续的交流与合作。我的联系方式是邮箱：wangss27@126.com，期望您能抽出一点时间！提前感谢！

**Comment by WentianZhang-ML** [comment]
shushenw,
您好，很抱歉我们没有及时回复。我们是把视频数据按照帧处理成图片，每个视频文件转化成以视频名命名的文件夹，文件夹下每一帧以数字编号命名，如第3帧，即3.jpg。可以具体参考utils/utils.py
下的sample_frames函数中文件格式的要求。

如有其它问题，欢迎及时提出，我们共同讨论学习。

祝好，
张文天
shushenw ***@***.***> 于2022年7月29日周五 17:02写道：

**Comment by shushenw** [comment]
张文天,
您好，非常感谢您的回复。我按照您的方法重新准备了数据库，顺利地训练了模型，训练结果跟您的结果相似。
再次感谢您的帮助，您的论文水平非常高，从中学习到了很多。希望下次能有继续向您讨教的机会。

再次感谢！祝好！
