### ISSUE TITLE
how to use dataset

### ISSUE THREAD

**Issue by wlz987** [WentianZhang-ML/FRT-PAD#2]
how to use those dataset ？？ 

这个数据集怎么用啊，CASIA_faceAntisp/test_release ，CASIA_faceAntisp/train_release ，里面全是 .avi. 没有 jpg

**Comment by WentianZhang-ML** [comment]
Our model was trained using only one frame information randomly selected from each video. This protocol was followed by previous SOTA face PAD methods.
