### ISSUE TITLE
No jpg files in datasets

### ISSUE THREAD

**Issue by bhoke** [WentianZhang-ML/FRT-PAD#3]
In line 43 of `data_find.py`: `path_list = glob.glob(dataset_path + '**/*.jpg', recursive=True)
`.

However, there is no `.jpg` in the MSU-MFSD dataset. Instead there are` .face `and `.mov` files which causes program to crash. Should the jpg images be cropped face images with indices in the `.face` files or the whole frame from the video files?

**Comment by bhoke** [comment]
Now I recognized that one random frame is used to train model in #2. 
Then I guess we can read corresponding video and select random frame from it and save it as jpg in the code. I am happy to contribute if you are open to contributions

**Comment by WentianZhang-ML** [comment]
Yes, we followed the same protocol with previous SOTA methods. And of course, you are welcome to contribute to our code. This project is open to everyone. You can update code or fix bugs (if there are) through PR!

**Comment by bhoke** [comment]
Can you share your final directory tree for any dataset? It seems that 
`data_find.py` line 54: `video_num = path_list[i].split('/')[-2].split('_')[1][-2:]` is not working when I save jpgs in the video directory of the dataset. Should I save jpgs into the directory which has same name with the video?

**Comment by WentianZhang-ML** [comment]
Yes, you are right. They are the same. For example, in CASIA-FASD, `'CASIA_faceAntisp/test_release/1/3/102.jpg'` means the 102nd image of 3.avi video in '1' folder.

**Comment by bhoke** [comment]
Is there just a single image per video or did you use all frames from video?

**Comment by WentianZhang-ML** [comment]
We sampled some frames from videos. You can refer to the protocol in [Single-Side Domain Generalization for Face Anti-Spoofing](https://arxiv.org/abs/2004.14043).
