### ISSUE TITLE
Pretrained GAT Weights

### ISSUE THREAD

**Issue by bhoke** [WentianZhang-ML/FRT-PAD#4]
I wrote an inference script to try pretrained weights, but the model predicts everything around 0.5. Then, I recognized that there is no pretrained model loaded for `GAT`/`Cross_Model_Adapter` network. By any chance, is it possible for you to share GAT pretrained network?

**Comment by WentianZhang-ML** [comment]
Sorry, we cannot provide the pretrained weights now.  According to our experience, it is no need to use pretrained model. Our proposed  network can easliy achieve convergence.
