### ISSUE TITLE
Testing on CASIA-FASD

### ISSUE THREAD

**Issue by angelabr** [WentianZhang-ML/FRT-PAD#5]
Hi,

I'm testing your pretrained model on CASIA-FASD and I always get similar values to spoof and life faces.
I'm using as input 256*256 images of faces, Face_recognition and Step_by_Step_Graph.

Is there anything I'm missing?

Thank you

**Comment by WentianZhang-ML** [comment]
Sorry, but we have not released our pretrained model. Do you try to train a model and find this problem?

**Comment by angelabr** [comment]
I have downloaded the four weight files you describe below Pre-trained Model Preparation
Are those not suitable for detection?

**Comment by WentianZhang-ML** [comment]
No, those are the parameters of face related tasks, which are only parts of our method (the blue block in the teaser). You can follow our codes and train your network with the given pretrianed parameters. It is pretty easy to complete the training.
