### ISSUE TITLE
GAT is related with batch size

### ISSUE THREAD

**Issue by Wei-Baldwin-Zeng** [WentianZhang-ML/FRT-PAD#6]
Hi, wonderful work!!!

I have a question about the method when testing. 
**It seems that the GraphAttentionLayer in GAT is related to the batch_size**. Say I trained the model with batch_size 32, when testing, I have to have the same batch_size 32 to load the model weights? Otherwise the feature size is different with training when testing with batch_size 1.

Hope to hear from you soon. Thank you so much.

**Comment by WentianZhang-ML** [comment]
Hi, thanks for trying our work. 
About your question, you are right. **The architecture of GAT is related to batch size.** If you use GAT as the cross-modal adapter, the batch size must be the same in the training and testing phase. But you can copy 1 sample to 32 in the channel-wise to continue the test and prediction when you trained the model with a batch size of 32.

**Comment by Wei-Baldwin-Zeng** [comment]
> Hi, thanks for trying our work. About your question, you are right. **The architecture of GAT is related to batch size.** If you use GAT as the cross-modal adapter, the batch size must be the same in the training and testing phase. But you can copy 1 sample to 32 in the channel-wise to continue the test and prediction when you trained the model with a batch size of 32.

Thank you so much for your quick response. But why should the GAT is related to batch size? As I understand, multiple batches in deep learning are just for speed up the training process, now the GAT seems to reshape the multiple batches to one huge batch, does it not support multiple batches for training? Or is there any way that I can also change the architecture of GAT so that it is not related to batch size.

Again, very wonderful work. Hope to hear your response.

**Comment by WentianZhang-ML** [comment]
Sorry for the late response. There was another way to support multiple batches, but we didn't find it until a year after we completed the project. You can refer to the solution in the [https://github.com/Diego999/pyGAT/issues/36](). But we have not tried it out. Please let me know if it works with our method after you use it!
